apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      run: myapp
  replicas: 3
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - name: myapp
        image: jayty/javawebapp:v1
        ports:
        - containerPort: 8080
